version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9013:80"
    volumes:
      - ./modules/:/var/www/html/herkul/modules/
      - ./themes/:/var/www/html/herkul/themes/
      - ./files/:/var/www/html/herkul/files/
      - ./config/:/var/www/html/herkul/config/
      - ./htaccess:/var/www/html/herkul/.htaccess
      - ./imagemagick-policy.xml:/var/www/html/herkul/imagemagick-policy.xml
    restart: "no"
