<?php
use Laminas\Http\Client;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
  $type = $template->label();
else:
  $type = "";
endif;
?>
<style>
  div[class="row"] div p{
    margin-bottom: 0%;
  }
  div[class="row"] div h3{
    margin-top: 13px;
  }
</style>
<?php
$name = $item->value('schema:givenName') . ' ' . $item->value('schema:familyName');
$resourceTemplateId = $item->resourceTemplate()->id();
$linkedResources = $item->subjectValues();

?>
<section>
<div class="container">
  <div>
    <div id="portal-breadcrumbs" class="breadcrumbs" style="display:block;">
      <span class="breadcrumb-item">
          <a href="<?php echo $site->url();?>">Home</a>
      </span>

      <span class="breadcrumb-item">
        <a href="<?php echo $site->url()."/find";?>">Search</a>         
      </span>    

      <span class="breadcrumb-item active">
        <?php if($resourceTemplateId == '6'): //test 2, prod 6
          echo $name;
        else:
          echo $item->displayTitle();
        endif;
         ?>
      </span>

    </div>
  </div>
 
  <h1>
  <?php if($resourceTemplateId == '6'): //test 2, prod 6
          echo $name;
        else:
          echo $item->displayTitle();
        endif;
  ?>
  </h1>
  <?php
    $viewerlink = '';$fls=[];
  ?>

    <div class="row">
      <?php if (!$embedMedia && $itemMedia): ?>
        <!-- afbeelding -->
        <div class="col-xs-12 col-md-2"> 
          <?php foreach($itemMedia as $media):?>
            <div class="has-text-centered">
              <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
              <?php $link = $url;?>
              <?php if($viewerlink):?>
                  <?php $link = $viewerlink;?>
              <?php endif;?> 
              <a target="_blank" href="<?php echo $link;?>"><img src="<?php echo $url;?>"></a>
            </div>
          <?php endforeach;?>
        </div>         
        <?php endif;?>

      <div class="col-xs-12 col-md-8">
        <div class="text-box" style="height:100%;margin-bottom:0;">

          <!-- PERSON -->
          <?php if($resourceTemplateId == '6'): ?><!-- test 2, prod 6 -->
          <?php
          $postal = $item->value('schema:postalCode') . ' ' . $item->value('schema:addressRegion');
          ?>
          <div class="row">
            <div class="col-xs-12 col-md-6" style="border-right:1px #ccc solid;">
                <h3>Address</h3>
                <a href="/memberdatabase/s/en/find?facet[schema:affiliation][]=<?php echo $item->value('schema:affiliation');?>"><?php echo $item->value('schema:affiliation');?></a>
                <p style="margin-bottom:0%;"><?php echo $item->value('schema:streetAddress');?></p>
                <?php if($item->value('schema:postOfficeBoxNumber')){ ?>
                <p><?php echo $item->value('schema:postOfficeBoxNumber');?></p>
                <?php }?>
                <p><?php echo $postal;?></p>
                <?php if($item->value('schema:contactPoint') != ''){?>
            <p><?php echo $item->value('schema:contactPoint')->asHtml();?></p>
            <?php } else {
              $htmlContent = $escape($item->value('schema:contactPoint')->asHtml());
              $con = preg_replace('/.*https:\/\/(.*)\/a.*/','https://${1}',$htmlContent);
              $cont = str_replace('&', '', htmlspecialchars($con));
              $contact = str_replace('amp;lt;', '', $cont);
            ?>
            <p><a href="<?php echo $contact;?>" target="_blank">Contact</a></p>
            <?php } ?>
              <?php
              $members = $item->value('schema:sourceOrganization', ['all' => true]);
              if($item->value('schema:sourceOrganization') && $members[0]->valueResource()){?>
              <h3>Organisation(s)</h3>
              <?php foreach($members as $member) {
                $linkedName = $member->valueResource()->displayTitle();
              ?>
              <p><a href="<?php echo $member;?>"><?php echo $linkedName;?></a></p>
              <?php }}
              ?>
              <?php
              $members = $item->value('schema:memberOf', ['all' => true]);
              if($item->value('schema:memberOf') && $members[0]->valueResource()){?>
              <h3>Working Group(s)</h3>  
              <?php foreach($members as $member) {
                $linkedName = $member->valueResource()->displayTitle();
              ?>
              <p><a href="<?php echo $member;?>"><?php echo $linkedName;?></a></p>
              <?php }}?>
            </div>
            <div class="col-xs-12 col-md-6">
              <h3>Professional profile</h3>
              <div style="margin-bottom: 13px;">
                <?php if($item->value('schema:roleName')){ ?>
                <p><?php echo $item->value('schema:roleName');?></p>
                <?php }?>
                <?php if($item->value('schema:hasOccupation')){ ?>
                <a href="/memberdatabase/s/en/find?facet[schema:hasOccupation][]=<?php echo $item->value('schema:hasOccupation');?>"><?php echo $item->value('schema:hasOccupation');?></a>
                <?php }?>
                <?php
                  $skills = $item->value('schema:skills', ['all' => true]);
                  if($item->value('schema:skills')){?>
                  <p style="margin-top: 8px;"><span>Field of work:</span>
                    <?php
                $skillList = implode(', ',$skills);
                echo $skillList;
                ?>
                </p>
                <?php }?>
                <?php
                  $keywords = $item->value('schema:keywords', ['all' => true]);
                  usort($keywords, function ($a, $b){
                    return strcmp($a->value('schema:keywords'), $b->value('schema:keywords'));
                  });
                  if($item->value('schema:keywords')){?>
                  <p style="margin-top: 8px;"><span>Research keywords: </span>
                    <?php
                $keywordList = implode(', ',$keywords);
                echo $keywordList;
                ?>
                </p>
                <?php }?>
                  </div>
                <?php if($item->value('schema:knowsAbout')){ //knows in test, knowsAbout op prod
                  echo $item->value('schema:knowsAbout')->asHtml();
                }
                ?>
                <?php if($item->value('schema:identifier')){
                  if(preg_match('/http/',$item->value('schema:identifier'))){
                    echo '<a href="' . $item->value('schema:identifier') . '">ORCID</a>';
                  } else {
                    echo '<p><span><strong>ORCID:</strong></span> ' . $item->value('schema:identifier') . '</p>';
                  }
                }
                ?>
                <?php if($item->value('schema:citation')){
                  echo $item->value('schema:citation')->asHtml();
                }
                ?>
                <?php
                  $links = $item->value('schema:relatedLink', ['all' => true]);
                  if($item->value('schema:relatedLink')){
                    foreach($links as $link) {
                      echo $link->asHtml();
                    } }?>
            </div>
          </div>

          <!-- ORGANISATION -->
          <?php elseif($resourceTemplateId == '9'): ?> <!-- test 3, prod 9-->
          <?php
          $postal = $item->value('schema:postalCode') . ' ' . $item->value('schema:addressRegion');
          ?>
          <div class="row">
            <div class="col-xs-12 col-md-6" style="border-right:1px #ccc solid;">
                <h3>Address</h3>
                <a href="/memberdatabase/s/en/find?facet[schema:affiliation][]=<?php echo $item->value('schema:affiliation');?>"><?php echo $item->value('schema:affiliation');?></a>
                <p style="margin-bottom:0%;"><?php echo $item->value('schema:streetAddress');?></p>
                <p><?php echo $item->value('schema:postOfficeBoxNumber');?></p>
                <p><?php echo $postal;?></p>
                <h3>Contact</h3>
                <?php
              $coordinators = $item->value('schema:contactPoint', ['all' => true]);
              if($item->value('schema:contactPoint') && $coordinators[0]->valueResource()){
              foreach($coordinators as $coordinator) {
                $linkedName = $coordinator->valueResource()->value('schema:givenName') . ' ' . $coordinator->valueResource()->value('schema:familyName');
              ?>
              <p><a href="<?php echo $coordinator;?>"><?php echo $linkedName;?></a></p>
              <?php }}?>
              <?php if($item->value('schema:citation')){?>
                <p><?php echo $item->value('schema:citation')->asHtml();?></p>
              <?php };?>
                
            </div>
            <div class="col-xs-12 col-md-6">
              <h3>Member(s)</h3>
              <!-- <?php
                  $linkedResource = $linkedResources["schema:sourceOrganization"];
                  //echo $linkedResource->resource()->value('schema:familyName');
                  foreach($linkedResource as $relatedResource){
                    $member = $relatedResource->resource()->value('schema:familyName');
                    echo $member;
                  }
              ?> -->
              <?php
              //$members = $item->value('schema:member', ['all' => true]);
              if(array_key_exists('schema:sourceOrganization', $linkedResources)){        
                $members = $linkedResources["schema:sourceOrganization"];      
                usort($members, function ($a, $b){
                  return strcmp($a->resource()->value('schema:familyName'), $b->resource()->value('schema:familyName'));
                });
                foreach($members as $member) {
                  $linkedName = $member->resource()->value('schema:givenName') . ' ' . $member->resource()->value('schema:familyName');
                ?>
                <p><a href="<?php echo $member->resource()->url();?>"><?php echo $linkedName;?></a></p>
              
              <?php }}?>

              <!-- <?php
              $members = $item->value('schema:member', ['all' => true]);
              usort($members, function ($a, $b){
                return strcmp($a->valueResource()->displayTitle(), $b->valueResource()->displayTitle());
              });
              if($item->value('schema:member') && $members[0]->valueResource()){
              foreach($members as $member) {
                $linkedName = $member->valueResource()->value('schema:givenName') . ' ' . $member->valueResource()->value('schema:familyName');
              ?>
              <p><a href="<?php echo $member;?>"><?php echo $linkedName;?></a></p>
              <?php }}?> -->
            </div>
          </div>

          <!-- WORKING GROUP -->
          <?php elseif($resourceTemplateId == '12'): ?> <!--test 4, prod 12-->
          <div class="row">
            <div class="col-xs-12 col-md-6" style="border-right:1px #ccc solid;">
            <?php if($item->value('schema:affiliation')){ ?>
            <h3>Institution</h3>
            <a href="/memberdatabase/s/en/find?facet[schema:affiliation][]=<?php echo $item->value('schema:affiliation');?>"><?php echo $item->value('schema:affiliation');?></a>
            <?php }?>
            <h3>Member(s)</h3>
              <?php
              //$members = $item->value('schema:member', ['all' => true]);
              if(array_key_exists('schema:memberOf', $linkedResources)){ 
              $members = $linkedResources["schema:memberOf"];
              usort($members, function ($a, $b){
                return strcmp($a->resource()->value('schema:familyName'), $b->resource()->value('schema:familyName'));
              });
              //if($item->value('schema:member') && $members[0]->valueResource()){
              foreach($members as $member) {
                $linkedName = $member->resource()->value('schema:givenName') . ' ' . $member->resource()->value('schema:familyName');
              ?>
              <p><a href="<?php echo $member->resource()->url();?>"><?php echo $linkedName;?></a></p>
              <?php }}?>
            </div>
            <div class="col-xs-12 col-md-6">
            <?php
              $keywords = $item->value('schema:keywords', ['all' => true]);
              usort($keywords, function ($a, $b){
                return strcmp($a->value('schema:keywords'), $b->value('schema:keywords'));
              });
              if($item->value('schema:keywords')){?>
                <h3>Research keywords</h3>
                <?php
                $keywordList = implode(', ',$keywords);
                echo $keywordList;
              }?>
              <?php if($item->value('schema:description')){ ?>
              <h3>Description</h3>
              <p><?php echo $item->displayDescription(); ?></p>
              <?php }?>
            </div>
          </div>
          <?php endif;?>
        </div>
      </div>
    </div>
    <!-- tweede rij vr Organisation keywords en description -->
    <?php if($resourceTemplateId == '9'): ?> <!-- test 3, prod 9 -->
    <div class="row">
      <div class="col-xs-12">
      <?php
      $keywords = $item->value('schema:keywords', ['all' => true]);
      usort($keywords, function ($a, $b){
        return strcmp($a->value('schema:keywords'), $b->value('schema:keywords'));
      });
      if($item->value('schema:keywords')){?>
        <h3>Research keywords</h3>
        <?php
                $keywordList = implode(', ',$keywords);
                echo $keywordList;
        }?>
        <?php if($item->value('schema:description')){ ?>
        <h3>Description</h3>
        <p><?php echo $item->displayDescription(); ?></p>
        <?php }?>
      </div>
    </div>
    <?php endif;?>
  </div>
</section>


<?php $this->trigger('view.show.after'); ?>
<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true
    });
    $('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    $('.slide-wrap').on('contextmenu', 'img', function(e){ 
      return false; 
    });

  });
</script>
