<div class="container container-block">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="kul-card-image card card-secondary card-50-50">
        <a class="card-img-link" href="">
          <div class="card-img-left" style="background-image: url(https://heritage.kuleuven.be/about_herkul/images/herkul3.jpg/image);">&nbsp;</div>
        </a>
        <div class="card-body">
          <h2 class="card-title"><a href="">An interdisciplinary institute</a></h2>
          <p>
          For a successful launch, HERKUL has gathered a  large group of experts from diverse fields associated with cultural heritage. Together, they will provide an expertise capable of facilitating intra-institutional collaborations, extra-institutional partnering, (inter)national visibility, as well as inter- and trans-disciplinary cooperation.
          </p>
          <!-- <p><a class="btn btn-ghost" href="">Lees verder</a></p> -->
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-primary">
        <div class="card-body">
          <h2 class="card-title"><a href=""></a>A trans-disciplinary institute</h2>
          <p>HERKUL aims to impact on institutional, national, European and international research programmes, while at the same time fully incorporating knowledge present in the critical mass and savoir faire of the KU Leuven to sustain both its own needs in the domain of cultural heritage, as well as of those beyond the institution.</p>
          <!-- <p><a class="btn btn-ghost-inv more" href="">More working groups</a></p> -->
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="card card-gray collection card card-body card-activity card-gray ">
        <h2 >
          <a href="">
            <span>Events</span>
          </a>
        </h2>
        <ul class="activity-list">
          <li><div class="main">
            <div class="date">Connecting Space & Time</div>
              <a href="" title="">
              HERKUL takes la condition humaine as its point of departure, entailing that our lives take part in history, as much as they make history. These are active and open-ended processes, characterised by change. Research on cultural heritage is instrumental to develop deeper interdisciplinary conceptualisations and epistemologies, and translate them into operational actions. For instance, HERKUL aims at connecting the KU Leuven institute within its historical and spatial context, not the least in regards to the celebration of its 600th anniversary in 2025.
              </a>
            </div>
          </li>
          <li><div class="main">
          <div class="date">Preservation & Management</div>
              <a href="" title="">
                Within the KU Leuven, a wide expertise on the material preservation of cultural heritage has been cultivated. HERKUL wishes to engage with safeguarding tangible, intangible and digital heritage, and sees potential in the fora on ethical dimension of cultural heritage, as well as the impact of climate change thereupon.
              </a>
            </div>
          </li>
        </ul>
        <p>
          <strong>
            <a class="more" href="">More events</a>
          </strong>  
        </p>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-gray">
        <div class="card-body">
          <h2>Research Priority</h2>

          <ul class="activity-list">
            <li><div class="main">
              <div class="date">Data science & knowledge sharing</div>
                <a href="" title="">
                Nowadays, the fast pace of development of data sciences within cultural heritage reflects a growing interest in digital humanities, and benefits the implemention of digital technologies facilitating the management of cultural heritage. This research priority taps into the important and vital digital infrastructure that has been set in place at KU Leuven.
                </a>
              </div>
            </li>
            <li><div class="main">
              <div class="date">Resource for well-being and sustainability</div>
                <a href="" title="">
                People are at the centre of cultural heritage. By understanding the contribution of cultural heritage to well-being and sustainable development, HERKUL involves society at large in the production, circulation and conservation of culture. Heritage is made, preserved, and enjoyed by the community.
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-contact">
        <div class="card-body">
          <h2>Contact HERKUL</h2>
          <p>
          If you are not satisfied with the entry for yourself in the database, 
if you wish to make a modification, be removed from the database, 
or add or remove any information and/or images and keywords, please contact us at:
          </p>
            <!-- <div class="vcard-item"><i class="material-icons vcard-icon">person</i>

            <div class="name">HERKUL</div>
            </div>

            <div class="vcard-item"><i class="material-icons vcard-icon">location_on</i>

            <div class="adr">
              <span>Address</span><br>
              <span>3000 Leuven</span><br>
              <span>Belgium</span></div>
            </div> -->

            <div class="vcard-item">
              <i class="material-icons vcard-icon">email</i>
              <div class="mail">  
                <div class="g-recaptcha btn button">
                <a href="mailto:herkul@kuleuven.be">herkul@kuleuven.be</a>
                </div>
              </div>
            </div>

            <!-- <div class="vcard-item">
              <i class="material-icons vcard-icon">phone</i>
              <div class="phone">
                <a href="tel:+32 16 32 09 29">+32 16 32 09 29</a
              ></div>
            </div>

            <div class="icons" style="margin:1rem 0"> -->
              <!-- ngIf: all.facebook != '' -->
              <!-- <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
              ngIf: all.twitter != '' -->
              <!-- <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-twitter fa-2x" aria-hidden="true"></i></a> -->
              <!-- ngIf: all.instagram != '' -->
              <!-- <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-instagram fa-2x" aria-hidden="true"></i></a> -->
              <!-- ngIf: all.youtube != '' -->
            <!-- </div>

            <p><strong><a class="more" href="">More about Herkul</a></strong></p>  -->
        </div>
      </div>
    </div>
  </div>
</div>
<?php if($block->dataValue('text')):?>
<div class="section text-only">
<?php else:?>
<div class="section" style="padding-bottom:2rem;">
<?php endif?>
    <div class="container" id="<?php echo $block->dataValue('title');?>">
      <?php if($block->dataValue('title')):?>
        <h2 class="title is-3"><?php echo $block->dataValue('title');?></h2>
      <?php endif;?>
      <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
        <div class="columns is-gapless">
          <div class="column is-12">
            <div class="content">
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
        </div>
      <?php endif;?>
      <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
        <div class="columns">
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text2');?>
            </div>
          </div>
        </div>
      <?php endif;?>
    </div>
</div>
