<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Medias are displayed through displayValues() for now.
// $medias = $contribution->valuesMedias();
// $embedMedia = $siteSetting('item_media_embed', false);

$siteSlug = $this->params()->fromRoute('site-slug');

$this->vars()->offsetSet('skipContributeCss', false);
$partial('contribute/site/contribution/asset-include');

$this->htmlElement('body')->appendAttribute('class', 'contribution resource show');
?>

<div class="contribute-resource conbribute-show container <?= $space && $space !== 'default' ? $space : '' ?>">

    <?= $this->pageTitle($contribution->displayTitle(), 2); ?>
    <h3><?= $translate('Contribution Status') ?></h3>

    <ul class="contribution-status list-group">
        <li class="contribution-resource list-group-item"><?= $resource ? $resource->linkPretty() : $escape($translate('Item is not yet visible in database')) ?></li>
        <li class="submitted list-group-item"><?= $escape($contribution->isSubmitted() ? $translate('Is submitted') : $translate('Item has not yet been submitted')) ?></li>
        <li class="reviewed list-group-item"><?= $escape($contribution->isReviewed() ? $translate('Is reviewed') : $translate('Item has not yet been reviewed')) ?></li>
    </ul>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php $this->trigger('view.show.before'); ?>

 <section class="section">
 <h3>Overview of item</h3>
    <?= $contribution->displayValues() ?>
 </section>



    <?php if (!$contribution->isSubmitted()): ?>
    <ul class="actions" data-message-remove-contribution="<?= $escapeAttr($translate('Are you sure to remove this contribution?')) ?>">
        <?php if ($contribution->userIsAllowed('update')): ?>
        <li><a class="btn btn-primary o-icon-edit button edit-button edit-contribution" href="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'edit', $space === 'guest')) ?>"><?= $escape($translate('Edit')) ?></a></li>
        <?php endif; ?>
        <li><a class="btn btn-secondary button submit-button submit-contribution" href="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'submit', $space === 'guest')) ?>"><?= $escape($translate('Submit')) ?></a></li>
        <?php if ($contribution->userIsAllowed('delete')): ?>
        <li><a class="btn btn-ghost o-icon-delete button delete-button remove-contribution" data-contribution-id="<?= $contribution->id() ?>" data-contribution-url="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'delete', $space === 'guest')) ?>"><?= $escape($translate('Delete')) ?></a></li>
        <?php endif; ?>
    </ul>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>

</div>
