<?php if($block->dataValue('text')):?>
<div class="section text-only">
<?php else:?>
<div class="section" style="padding-bottom:2rem;">
<?php endif?>
    <div class="container" id="<?php echo $block->dataValue('title');?>">
      <?php if($block->dataValue('title')):?>
        <h1><?php echo $block->dataValue('title');?></h1>
      <?php endif;?>
      <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
        <div class="row">
          <div class="col-md-12">
            <div class="content">
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
        </div>
      <?php endif;?>
      <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
        <div class="row">
          <div class="col-md-6">
            <div class="content">
            <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <div class="col-md-6">
            <div class="content">
            <?php echo $block->dataValue('text2');?>
            </div>
          </div>
        </div>
      <?php endif;?>
    </div>
</div>
